version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Mudar123
      MYSQL_DATABASE: erp_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "8081:3306"
    volumes:
      - ./data:/var/lib/mysql